/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package amlahproject;

import com.itextpdf.text.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class pdfmaker extends javax.swing.JFrame {

    /**
     * Creates new form pdfmaker
     */
    public pdfmaker() {
        initComponents();
        Toolkit tk= Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
         int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        disc = new javax.swing.JTextField();
        abaad = new javax.swing.JTextField();
        pricef = new javax.swing.JTextField();
        chooseimage = new javax.swing.JButton();
        imagelabel = new javax.swing.JLabel();
        additemb = new javax.swing.JButton();
        createpdfb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editb = new javax.swing.JButton();
        filechooserout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        minimize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(244, 208, 63));

        jPanel2.setBackground(new java.awt.Color(112, 112, 105));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("أسم الصنف");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("وصف الصنف ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("أبعاد الصنف");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("السعر");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discActionPerformed(evt);
            }
        });

        abaad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaadActionPerformed(evt);
            }
        });

        chooseimage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chooseimage.setText("اختيار صورة");
        chooseimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseimageActionPerformed(evt);
            }
        });

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        additemb.setText("اضافة المنتج");
        additemb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additembActionPerformed(evt);
            }
        });

        createpdfb.setText("انهاء");
        createpdfb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createpdfbActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setForeground(new java.awt.Color(46, 64, 83));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " السطر", "ID", "اسم الصنف", "وصف الصنف", "أمتداد الصورة", "أبعاد الصنف", "السعر"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(46, 64, 83));
        jScrollPane1.setViewportView(jTable1);

        editb.setText("تعديل");
        editb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbActionPerformed(evt);
            }
        });

        filechooserout.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createpdfb, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(additemb, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editb, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(220, 220, 220))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(185, 185, 185)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pricef, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(filechooserout, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(id)
                                        .addComponent(disc)
                                        .addComponent(name)
                                        .addComponent(chooseimage, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                            .addComponent(abaad, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(disc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chooseimage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filechooserout, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abaad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(additemb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pricef, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createpdfb, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("مكتبة ومعرض طيور الجنة");

        minimize.setText("🗕 ");
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(590, 590, 590)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minimize)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abaadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abaadActionPerformed

//      public void onEndPage(PdfWriter writer, Document document) {
//        ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_CENTER, new Phrase("page " + document.getPageNumber()), 550, 30, 0);
//    }
    public static Font  f=FontFactory.getFont("c:/windows/fonts/simpo.ttf", BaseFont.IDENTITY_H,14);
    
    public  void addfooer( PdfWriter writer,Document document){
     
    }
    public void createPdf(String dest) throws IOException, DocumentException {
        Document document = new Document();
         PdfWriter writer= PdfWriter.getInstance(document, new FileOutputStream(dest));
         Rectangle rect = new Rectangle(30, 30, 550, 800);
        writer.setBoxSize("art", rect);
        HeaderFooterPageEvent event = new HeaderFooterPageEvent();
        writer.setPageEvent(event);
    
                 document.open();
                 
        PdfPTable table = new PdfPTable(6);
        table.setWidthPercentage(100);
        //table.setWidths(new int[]{1, 2,});
        //table heading
       
      

          //اضافة الانبوت
         for(int i=0;i<data.size()/6;i++){
             for(int j=0;j<6;j++){
                 if (j==3){
                    table.addCell(createImageCell(data.get(i*6+3)));
                 }
                 //عشان نتحكم بلون السعر اضافة السعر
                 else if(j==5){
                    PdfPCell cell = new PdfPCell();
                    cell.setRunDirection(writer.RUN_DIRECTION_RTL);
                    f.setColor(BaseColor.RED);
                    Paragraph p=new Paragraph(data.get((i*6)+j), f);
                    p.setAlignment(PdfPCell.ALIGN_CENTER);
                    cell.addElement(p);
                    table.addCell(cell);
                    f.setColor(BaseColor.BLACK);
                 }
                 else if(j==4){
                    PdfPCell cell = new PdfPCell();
                    cell.setRunDirection(writer.RUN_DIRECTION_RTL);
                   
                    Paragraph p=new Paragraph(data.get((i*6)+j)+"سم ", f);
                    p.setAlignment(PdfPCell.ALIGN_CENTER);
                    cell.addElement(p);
                    table.addCell(cell);
                    
                 }
                 else{
                    PdfPCell cell = new PdfPCell();
                    cell.setRunDirection(writer.RUN_DIRECTION_RTL);
                    Paragraph p=new Paragraph(data.get((i*6)+j), f);
                    p.setAlignment(PdfPCell.ALIGN_CENTER);
                    cell.addElement(p);
                    table.addCell(cell);}

          }
          }
        
       
        document.add(table);
        document.close();
        // onEndPage(writer,document);
          System.out.println("page number add");

    
    }
    
    public  PdfPCell createImageCell(String path) throws DocumentException, IOException {
        Image img = Image.getInstance(path);
          Rectangle r =new Rectangle(80,50);
           img.scaleToFit(r);
      PdfPCell cell = new PdfPCell();
        cell.setBorderColor(BaseColor.BLACK);
        
         cell.setVerticalAlignment(r.ALIGN_CENTER);
         cell.setHorizontalAlignment(r.ALIGN_CENTER);
           img.setAlignment(PdfPCell.ALIGN_CENTER);
               cell.addElement(img);
//              Rectangle r2 =new Rectangle(186,188);
//           img.scaleToFit(r2);
         
         System.out.println("image created");
        return cell;
       
    }
    
        
//     public static PdfPCell createTextCell(String text) throws DocumentException, IOException {
//        PdfPCell cell = new PdfPCell();
//        // cell.setRunDirection();
//        Paragraph p = new Paragraph(text);
//        p.setAlignment(Element.ALIGN_CENTER);
//        cell.addElement(p);
//        cell.setVerticalAlignment(Element.ALIGN_CENTER);
//       cell.setBorderColor(BaseColor.BLACK);
//        return cell;
//     }
//    
    
    
    
    
     String pdfname="";
    private void createpdfbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createpdfbActionPerformed
         JFrame f = new JFrame(); 
         JFrame f2 = new JFrame();  
          
                 int bool=JOptionPane.showConfirmDialog( f2,"هل تريد انشاء ملفpdf  ","finish",
             JOptionPane.YES_NO_OPTION);
             
           if (bool==YES_OPTION){
               if(data.isEmpty()){
                  JFrame x = new JFrame(); 
                JOptionPane.showMessageDialog(x,"الرجاء ادخال بيانات ");}
               else{
             pdfname=JOptionPane.showInputDialog(f,"أدخل اسم الملف "); 
             if(pdfname.equals("")){
                JFrame e = new JFrame(); 
                JOptionPane.showMessageDialog(e,"الادخال غير صحيح");}
            
             else{
                 
                System.out.println(pdfname);
                String path =new String(System.getProperty("user.home") + "\\OneDrive\\Desktop");
                 System.out.println(path);
                 try {
                // createImageCell()
            
                //to create the pdf
                
                    
                 createPdf(path+"\\"+pdfname+".pdf");
                 } catch (IOException ex) {
                  Logger.getLogger(pdfmaker.class.getName()).log(Level.SEVERE, null, ex);
                  } catch (DocumentException ex) {
                 Logger.getLogger(pdfmaker.class.getName()).log(Level.SEVERE, null, ex);
                 }
                  System.out.println("pdf created");
                 JOptionPane.showMessageDialog(this, "تم انشاء الملف بنجاح");
                      System.exit(0);}}}
        else if (bool==NO_OPTION){
            System.exit(0);
        }
           else;
    }//GEN-LAST:event_createpdfbActionPerformed

    
    
    
    
    //the array list
     ArrayList<String> data = new ArrayList<String>();
     int rownum1=0;
    private void additembActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additembActionPerformed
         // :if there id any empty feilds
        
         if (id.getText().equals("") ||name.getText().equals("")||disc.getText().equals("")||abaad.getText().equals("")||pricef.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please enter all data"); 
         }
        //chek if there is just numbers
//        else if (numf.getText().matches("[a-zA-Z]+"))
//            
//            JOptionPane.showMessageDialog(this, "الرجاء ادخال ارقام فقط في خانة الرقم"); 
//        else if(sizef.getText().matches("[a-zA-Z]+"))
//            JOptionPane.showMessageDialog(this, "الرجاء ادخال ارقام فقط في خانة الحجم"); 
         else if(pricef.getText().matches("[a-zA-Z]+"))
            JOptionPane.showMessageDialog(this, "الرجاء ادخال ارقام فقط في خانة السعر"); 
        else if (imgpath.equals(""))
            
            JOptionPane.showMessageDialog(this, "الرجاء اختيار صورة"); 
        else{
            //add data
      data.add(id.getText());
       data.add(name.getText());
        data.add(disc.getText());
        //data.add(abaad.getText());
        
        //add img to the arraylist its in the 3 cell
         data.add(imgpath);
         
        // data.add(disc.getText());
        data.add(abaad.getText());
           data.add(pricef.getText());
           
//              data.add(pricef.getText());
//              data.add(abaad.getText());
//              data.add(imgpath);
//              data.add(disc.getText());
//              data.add(name.getText());
//              data.add(id.getText());
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          
          rownum1++;
            for(int i=data.size()/6-1;i<data.size()/6;i++){
                
                  model.addRow(new Object[]{rownum1,data.get(i*6), data.get(i*6+1), data.get(i*6+2),data.get(i*6+3),data.get(i*6+4),data.get(i*6+5)});
            }
           
        
                 
       //set all fields to empty
      id.setText("");
        name.setText("");
        //img
         filechooserout.setText("");
        abaad.setText("");
         disc.setText("");
        pricef.setText("");
        imgpath="";
        
        
        
        }
        
    }//GEN-LAST:event_additembActionPerformed
public ImageIcon resize(String imgPath)
  {
    ImageIcon path = new ImageIcon(imgPath);
        java.awt.Image img = path.getImage();
     java.awt.Image newImg = img.getScaledInstance(imagelabel.getWidth(), imagelabel.getHeight(), java.awt.Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
  }
    
    public String imgpath="";
    private void chooseimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseimageActionPerformed
       JFileChooser choos =new JFileChooser();//عرفنا الفايل
//     choos.setCurrentDirectory(new File("C:\\Users\\Cakow\\Desktop"));
       FileNameExtensionFilter f= new FileNameExtensionFilter("Image Files", "jpg","bmp","png","jfif");
       choos.setFileFilter(f);
       int responce =choos.showSaveDialog(null);
       if( responce == JFileChooser.APPROVE_OPTION){
           File fimage =new File(choos.getSelectedFile().getAbsolutePath());
         imgpath=new String(fimage.getAbsolutePath());
          filechooserout.setText(fimage.getAbsolutePath());
           imagelabel.setIcon(resize(imgpath));
       }
    }//GEN-LAST:event_chooseimageActionPerformed

    private void discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discActionPerformed

    
    
    
    
    private int showInputDialog()
{
    String inputValue = JOptionPane.showInputDialog("أدخل رقم السطر اللذي تريد تعديل");
      int editrownum=0;
    try{
            editrownum = Integer.parseInt(inputValue);
            System.out.println("the inserted num"+editrownum);
        }
        catch (NumberFormatException ex){
            //ex.printStackTrace();
            // JFrame e = new JFrame(); 
           // JOptionPane.showMessageDialog(rootPane,"الرجاء ادخال رقم");
        }
    if(inputValue == null || inputValue.isEmpty() )
        return -1;
    else if(!inputValue.matches("[0-9]+")||editrownum> data.size()/6||editrownum<0)
    {
       // editrownum = showInputDialog();
          JFrame e = new JFrame(); 
            JOptionPane.showMessageDialog(e,"الادخال غير صحيح");
            return -1;
    }
     else    
    return editrownum;
}
    
    private void editbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbActionPerformed
        // TODO add your handling code here:
         JFrame rownumf = new JFrame(); 
        JFrame f2 = new JFrame();  
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //rownum=JOptionPane.showInputDialog(rownumf,"أدخل رقم السطر اللذي تريد تعديله");   
        int rownum=showInputDialog();
        if (rownum==-1 );
        
        else{
 
         String[] options = {"ID", "أسم الصنف", "وصف الصنف","الصورة", "أبعاد الصنف", "السعر",};
      ImageIcon icon = null;
        String editop = (String)JOptionPane.showInputDialog(null, "اختار ما الذي تريد تعديله", 
                "edit", JOptionPane.QUESTION_MESSAGE,icon, options, options[2]);
        System.out.println(editop);
        
        switch(editop) {
  case "ID":{
      String edit = JOptionPane.showInputDialog("ادخل ال"+" ID "+"الجديد");
    data.set((rownum-1)*6, edit);
    jTable1.setValueAt(edit, rownum-1, 1);
            break;}
  case "أسم الصنف":{
        String edit = JOptionPane.showInputDialog("أدخل أسم الصنف الجديد");
    data.set((rownum-1)*6+1, edit);
     model.setValueAt(edit, rownum-1, 2);
    break;}
  case "وصف الصنف":{
        String edit = JOptionPane.showInputDialog("أدخل  وصف الصنف الجديد");
    data.set((rownum-1)*6+2, edit);
    
    model.setValueAt(edit, rownum-1, 3);
    break;}
  case "الصورة":{
         JFileChooser choos =new JFileChooser();//عرفنا الفايل
//     choos.setCurrentDirectory(new File("C:\\Users\\Cakow\\Desktop"));
       FileNameExtensionFilter f= new FileNameExtensionFilter("Image Files", "jpg","bmp","png");
       choos.setFileFilter(f);
       int responce =choos.showSaveDialog(null);
       if( responce == JFileChooser.APPROVE_OPTION){
           File fimage =new File(choos.getSelectedFile().getAbsolutePath());
         imgpath=new String(fimage.getAbsolutePath());
           imagelabel.setIcon(resize(imgpath));
          
       }
    
    data.set((rownum-1)*6+3, imgpath);
     model.setValueAt(imgpath, rownum-1, 4);
    break;}
   case "أبعاد الصنف":{
        String edit = JOptionPane.showInputDialog("أدخل أبعاد الصنف الجديد");
    
    data.set((rownum-1)*6+4, edit);
    
      model.setValueAt(edit, rownum-1, 5);
    break;}
  
  default:{
    String edit = JOptionPane.showInputDialog("أدخل السعر الجديد");
    
    data.set((rownum-1)*6+5, edit);
           model.setValueAt(edit, rownum-1, 6);}
}
        
        
        
        
        
//          if (JOptionPane.showConfirmDialog( f2,"أدخل رقم السطر اللذي تريد تعديله ","تعديل",
//            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
//       
//        
//          
//     
//       
//        System.out.println("pdf created");
//         JOptionPane.showMessageDialog(this, "pdf created sucsesfully"); }
//         else {
//     System.exit(0);}
        }
    }//GEN-LAST:event_editbActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        // TODO add your handling code here:
        minimize.setBackground(Color.LIGHT_GRAY);
        setState(JFrame.ICONIFIED);
        
    }//GEN-LAST:event_minimizeActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pdfmaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pdfmaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pdfmaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pdfmaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
        
                new pdfmaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abaad;
    private javax.swing.JButton additemb;
    private javax.swing.JButton chooseimage;
    private javax.swing.JButton createpdfb;
    private javax.swing.JTextField disc;
    private javax.swing.JButton editb;
    private javax.swing.JLabel filechooserout;
    private javax.swing.JTextField id;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton minimize;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pricef;
    // End of variables declaration//GEN-END:variables
}

